before:
  hooks:
    - go mod download
    - go test ./...
builds:
  - main: ./cmd/yaml-docs
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goos:
      - linux
      - darwin
      - windows
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

signs:
- artifacts: checksum

nfpms:
- vendor: yaml-docs
  homepage: https://github.com/theEndBeta/yaml-docs
  maintainer: theEndBeta
  description: A tool for automatically generating markdown documentation for yaml charts
  license: GNU General Public License v3.0
  formats:
  - deb
  - rpm
  replacements:
    amd64: x86_64
    linux: Linux

brews:
  - tap:
      owner: theEndBeta
      name: homebrew
    folder: Formula
    homepage: https://github.com/theEndBeta/yaml-docs
    description: Automatically generate markdown documentation for yaml charts
    install: |
      bin.install "yaml-docs"
    test: |
      system "#{bin}/yaml-docs --version"
dockers:
  - goarch: amd64
    use_buildx: true
    image_templates:
      - thendbeta/{{ .ProjectName }}:{{ .Tag }}-amd64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/theEndBeta/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/theEndBeta/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPLv3
  - goarch: arm64
    use_buildx: true
    image_templates:
      - thendbeta/{{ .ProjectName }}:{{ .Tag }}-arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/theEndBeta/{{ .ProjectName }}
      - --label=org.opencontainers.image.source=https://github.com/theEndBeta/{{ .ProjectName }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=GPLv3
docker_manifests:
- name_template: thendbeta/{{ .ProjectName }}:{{ .Tag }}
  image_templates:
    - thendbeta/{{ .ProjectName }}:{{ .Tag }}-amd64
    - thendbeta/{{ .ProjectName }}:{{ .Tag }}-arm64
    - thendbeta/{{ .ProjectName }}:{{ .Tag }}-arm64v6
    - thendbeta/{{ .ProjectName }}:{{ .Tag }}-arm64v7
- name_template: thendbeta/{{ .ProjectName }}:latest
  image_templates:
    - thendbeta/{{ .ProjectName }}:{{ .Tag }}-amd64
    - thendbeta/{{ .ProjectName }}:{{ .Tag }}-arm64
    - thendbeta/{{ .ProjectName }}:{{ .Tag }}-arm64v6
    - thendbeta/{{ .ProjectName }}:{{ .Tag }}-arm64v7
