repos:
  - repo: https://github.com/theEndBeta/yaml-docs
    rev: v1.2.0
    hooks:
      - id: yaml-docs
        args:
          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./_templates.gotmpl

          # Repeating the flag adds this to the list, now [./_templates.gotmpl, README.md.gotmpl]
          # A base filename makes it relative to each chart directory found
          - --template-files=README.md.gotmpl

          - --values-files=main.yml
