name: Build

on:
  push:
    branches:
    - "*"
    tags-ignore:
    - "*"
  pull_request:
    types: [opened, reopened]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Log into quay,io
        uses: redhat-actions/podman-login@v1
        with:
          username: andbron+andbron_github
          password: ${{ secrets.andbron_QUAY }}
          registry: quay.io
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --snapshot --skip-sign
