name: Release

on:
  push:
    tags:
    - "*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - name: Log into quay,io
        uses: redhat-actions/podman-login@v1
        with:
          username: theendbeta+theendbeta_github
          password: ${{ secrets.THEENDBETA_QUAY }}
          registry: quay.io
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.NORWOODJ_ORG_TOKEN }}
